name: Deploy CSharpStrings .NET9 VM

on:
  push:
    branches:
      - develop_soluzione_A_deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          
      - name: Publish
        run: dotnet publish ./src/CSharpStrings/CSharpStrings.csproj -c Release -o publish

      - name: Deploy via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: deployer
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "publish/*"
          target: "/home/deployer/app"

      - name: Restart App via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: deployer
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart csharpsales.service